//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "account_platform_data"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Default)]
pub struct Model {
    pub id: i64,
    pub account: i64,
    pub platform: i64,
    pub key: String,
    pub value: String,
    pub created_at: i64,
    pub updated_at: i64,
    pub deleted_at: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    Account,
    Platform,
    Key,
    Value,
    CreatedAt,
    UpdatedAt,
    DeletedAt,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i64;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    AccountPlatforms,
    Accounts,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::BigInteger.def(),
            Self::Account => ColumnType::BigInteger.def(),
            Self::Platform => ColumnType::BigInteger.def(),
            Self::Key => ColumnType::String(Some(128u32)).def(),
            Self::Value => ColumnType::Text.def(),
            Self::CreatedAt => ColumnType::BigInteger.def(),
            Self::UpdatedAt => ColumnType::BigInteger.def(),
            Self::DeletedAt => ColumnType::BigInteger.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::AccountPlatforms => Entity::belongs_to(super::account_platforms::Entity)
                .from(Column::Platform)
                .to(super::account_platforms::Column::Id)
                .into(),
            Self::Accounts => Entity::belongs_to(super::accounts::Entity)
                .from(Column::Account)
                .to(super::accounts::Column::Id)
                .into(),
        }
    }
}

impl Related<super::account_platforms::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AccountPlatforms.def()
    }
}

impl Related<super::accounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Accounts.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
