//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

pub use super::account_platform_data::Entity as AccountPlatformData;
pub use super::account_platforms::Entity as AccountPlatforms;
pub use super::accounts::Entity as Accounts;
